#!/usr/bin/expect -f
set timeout 60
set password "AYoEI^3S@lf9Tp90Fl"

spawn scp -o StrictHostKeyChecking=no /Users/changpengcheng/MT/ssl_temp/motizhidi.cn_nginx/motizhidi.cn_bundle.crt /Users/changpengcheng/MT/ssl_temp/motizhidi.cn_nginx/motizhidi.cn.key /Users/changpengcheng/MT/ssl_temp/motizhidi.cn.conf root@110.42.230.103:/tmp/

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    eof
}
